apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: intro-to-mltp

# Default configuration
build:
  artifacts:
    - image: mythical-beasts-server
      context: source
      docker:
        dockerfile: docker/Dockerfile
        buildArgs:
          SERVICE: mythical-beasts-server
      sync:
        manual:
          - src: "mythical-beasts-server/**/*.js"
            dest: /usr/src/app/
          - src: "common/**/*.js"
            dest: /usr/src/app/
    - image: mythical-beasts-requester
      context: source
      docker:
        dockerfile: docker/Dockerfile
        buildArgs:
          SERVICE: mythical-beasts-requester
      sync:
        manual:
          - src: "mythical-beasts-requester/**/*.js"
            dest: /usr/src/app/
          - src: "common/**/*.js"
            dest: /usr/src/app/
    - image: mythical-beasts-recorder
      context: source
      docker:
        dockerfile: docker/Dockerfile
        buildArgs:
          SERVICE: mythical-beasts-recorder
      sync:
        manual:
          - src: "mythical-beasts-recorder/**/*.js"
            dest: /usr/src/app/
          - src: "common/**/*.js"
            dest: /usr/src/app/

deploy:
  helm:
    releases:
      - name: grafana-mltp-stack
        chartPath: k8s-helm/grafana-mltp-stack
        valuesFiles:
          - k8s-helm/grafana-mltp-stack/values.yaml
        setValueTemplates:
          # Override image repositories for dev mode
          microservices.server.image.repository: mythical-beasts-server
          microservices.server.image.tag: latest
          microservices.server.image.pullPolicy: Never
          microservices.requester.image.repository: mythical-beasts-requester
          microservices.requester.image.tag: latest
          microservices.requester.image.pullPolicy: Never
          microservices.recorder.image.repository: mythical-beasts-recorder
          microservices.recorder.image.tag: latest
          microservices.recorder.image.pullPolicy: Never
          # Enable development mode configurations
          development.localConfigs.enabled: false  # Keep configs in ConfigMaps for simplicity in dev mode
        namespace: mltp-dev

# Development profile with faster rebuilds and file sync
profiles:
  - name: dev
    build:
      artifacts:
        - image: mythical-beasts-server
          context: source
          docker:
            dockerfile: docker/Dockerfile
            buildArgs:
              SERVICE: mythical-beasts-server
          sync:
            manual:
              - src: "mythical-beasts-server/**/*.js"
                dest: /usr/src/app/
                strip: "mythical-beasts-server/"
              - src: "common/**/*.js"
                dest: /usr/src/app/
                strip: "common/"
        - image: mythical-beasts-requester
          context: source
          docker:
            dockerfile: docker/Dockerfile
            buildArgs:
              SERVICE: mythical-beasts-requester
          sync:
            manual:
              - src: "mythical-beasts-requester/**/*.js"
                dest: /usr/src/app/
                strip: "mythical-beasts-requester/"
              - src: "common/**/*.js"
                dest: /usr/src/app/
                strip: "common/"
        - image: mythical-beasts-recorder
          context: source
          docker:
            dockerfile: docker/Dockerfile
            buildArgs:
              SERVICE: mythical-beasts-recorder
          sync:
            manual:
              - src: "mythical-beasts-recorder/**/*.js"
                dest: /usr/src/app/
                strip: "mythical-beasts-recorder/"
              - src: "common/**/*.js"
                dest: /usr/src/app/
                strip: "common/"
    deploy:
      helm:
        releases:
          - name: grafana-mltp-stack
            chartPath: k8s-helm/grafana-mltp-stack
            valuesFiles:
              - k8s-helm/grafana-mltp-stack/values.yaml
              - k8s-helm/dev-values.yaml
            setValueTemplates:
              # Override image repositories for dev mode
              microservices.server.image.repository: mythical-beasts-server
              microservices.server.image.tag: latest
              microservices.server.image.pullPolicy: Never
              microservices.requester.image.repository: mythical-beasts-requester
              microservices.requester.image.tag: latest
              microservices.requester.image.pullPolicy: Never
              microservices.recorder.image.repository: mythical-beasts-recorder
              microservices.recorder.image.tag: latest
              microservices.recorder.image.pullPolicy: Never
              # Enable development mode features
              development.localConfigs.enabled: false
              development.mode: true
            namespace: mltp-dev

  # Production profile using registry images
  - name: prod
    deploy:
      helm:
        releases:
          - name: grafana-mltp-stack
            chartPath: k8s-helm/grafana-mltp-stack
            valuesFiles:
              - k8s-helm/grafana-mltp-stack/values.yaml
            setValueTemplates:
              development.localConfigs.enabled: false
              development.mode: false
            namespace: mltp-prod

# Port forwarding for easy access during development
portForward:
  - resourceType: service
    resourceName: grafana-mltp-stack-grafana
    namespace: mltp-dev
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: grafana-mltp-stack-mythical-server
    namespace: mltp-dev
    port: 4000
    localPort: 4000
  - resourceType: service
    resourceName: grafana-mltp-stack-mythical-requester
    namespace: mltp-dev
    port: 4001
    localPort: 4001
  - resourceType: service
    resourceName: grafana-mltp-stack-mythical-recorder
    namespace: mltp-dev
    port: 4002
    localPort: 4002
