{{- if .Values.observability.alloy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-alloy
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "alloy" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grafana-mltp-stack.componentSelectorLabels" (list . "alloy") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana-mltp-stack.labels" . | nindent 8 }}
        {{- include "grafana-mltp-stack.componentLabels" "alloy" | nindent 8 }}
    spec:
      {{- include "grafana-mltp-stack.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "grafana-mltp-stack.serviceAccountName" . }}
      {{- include "grafana-mltp-stack.podSecurityContext" . | nindent 6 }}
      containers:
        - name: alloy
          {{- include "grafana-mltp-stack.securityContext" . | nindent 10 }}
          image: "{{ .Values.observability.alloy.image.repository }}:{{ .Values.observability.alloy.image.tag }}"
          imagePullPolicy: {{ .Values.observability.alloy.image.pullPolicy }}
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --stability.level=public-preview
            - /etc/alloy/config.alloy
          ports:
            - name: http
              containerPort: {{ .Values.observability.alloy.ports.http }}
              protocol: TCP
            - name: alt
              containerPort: {{ .Values.observability.alloy.ports.alt }}
              protocol: TCP
            - name: jaeger
              containerPort: {{ .Values.observability.alloy.ports.jaeger }}
              protocol: TCP
            - name: zipkin
              containerPort: {{ .Values.observability.alloy.ports.zipkin }}
              protocol: TCP
            - name: otlp-grpc
              containerPort: {{ .Values.observability.alloy.ports.otlp_grpc }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ .Values.observability.alloy.ports.otlp_http }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.observability.alloy.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana-mltp-stack.fullname" . }}-alloy-config
      {{- include "grafana-mltp-stack.nodeSelector" . | nindent 6 }}
      {{- include "grafana-mltp-stack.affinity" . | nindent 6 }}
      {{- include "grafana-mltp-stack.tolerations" . | nindent 6 }}
{{- end }}
