{{- if .Values.observability.alloy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-alloy-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "alloy" | nindent 4 }}
data:
  config.alloy: |
    {{- if and .Values.configOverrides.alloy (ne .Values.configOverrides.alloy "") }}
    {{- .Values.configOverrides.alloy | nindent 4 }}
    {{- else }}
    {{- tpl (.Files.Get "configs/alloy-config.alloy") . | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-alloy-endpoints
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "alloy" | nindent 4 }}
data:
  endpoints.json: |
    {{- .Files.Get "configs/alloy-endpoints.json" | nindent 4 }}
{{- end }}
