{{- if .Values.beyla.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 4 }}
data:
  beyla-config.yml: |
{{- .Files.Get "configs/beyla-config.yml" | replace "__CLUSTER_NAME__" (.Values.global.clusterName | default "local") | replace "__ALLOY_ENDPOINT__" (printf "http://%s-alloy.%s.svc.cluster.local:4317" (include "grafana-mltp-stack.fullname" .) (.Values.global.namespace | default .Release.Namespace)) | nindent 4 }}
{{- end }}
