{{- if .Values.beyla.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-beyla
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "grafana-mltp-stack.componentSelectorLabels" (list . "beyla") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana-mltp-stack.labels" . | nindent 8 }}
        {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana-mltp-stack.serviceAccountName" . }}
      hostPID: true  # Required for eBPF instrumentation
      {{- include "grafana-mltp-stack.podSecurityContext" . | nindent 6 }}
      containers:
        - name: beyla
          image: "{{ .Values.beyla.image.repository }}:{{ .Values.beyla.image.tag }}"
          imagePullPolicy: {{ .Values.beyla.image.pullPolicy }}
          securityContext:
            privileged: true  # Required for eBPF
            readOnlyRootFilesystem: true
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/config/beyla-config.yml"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ include "grafana-mltp-stack.fullname" . }}-alloy.{{ .Values.global.namespace }}.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          resources:
            {{- toYaml .Values.beyla.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: var-run-beyla
              mountPath: /var/run/beyla
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-config
        - name: var-run-beyla
          emptyDir: {}
      {{- include "grafana-mltp-stack.nodeSelector" . | nindent 6 }}
      {{- include "grafana-mltp-stack.affinity" . | nindent 6 }}
      {{- include "grafana-mltp-stack.tolerations" . | nindent 6 }}
{{- end }}
