{{- if .Values.beyla.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 4 }}
data:
  beyla-config.yml: |
    {{- if and .Values.configOverrides.beyla (ne .Values.configOverrides.beyla "") }}
    {{- .Values.configOverrides.beyla | nindent 4 }}
    {{- else }}
    {{- tpl (.Files.Get "configs/beyla-config.yml") . | nindent 4 }}
    {{- end }}
{{- end }}
