{{- if .Values.beyla.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-beyla
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "grafana-mltp-stack.componentSelectorLabels" (list . "beyla") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana-mltp-stack.labels" . | nindent 8 }}
        {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana-mltp-stack.serviceAccountName" . }}
      hostPID: true  # Required for eBPF instrumentation
      {{- include "grafana-mltp-stack.podSecurityContext" . | nindent 6 }}
      containers:
        - name: beyla
          image: "{{ .Values.beyla.image.repository }}:{{ .Values.beyla.image.tag }}"
          imagePullPolicy: {{ .Values.beyla.image.pullPolicy }}
          securityContext:
            privileged: true  # Required for eBPF
            readOnlyRootFilesystem: true
          envFrom:
            # Load non-sensitive environment variables from ConfigMap
            - configMapRef:
                name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-env
          resources:
            {{- toYaml .Values.beyla.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.development.localConfigs.enabled }}
            - name: config-volume
              mountPath: /config/beyla-config.yml
              subPath: {{ base .Values.development.localConfigs.beyla.configPath }}
              readOnly: true
            {{- else }}
            - name: config
              mountPath: /config
            {{- end }}
            - name: var-run-beyla
              mountPath: /var/run/beyla
      volumes:
        {{- if .Values.development.localConfigs.enabled }}
        - name: config-volume
          hostPath:
            path: {{ .Values.development.localConfigs.basePath }}/{{ .Values.development.localConfigs.beyla.configPath }}
            type: File
        {{- else }}
        - name: config
          configMap:
            name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-config
        {{- end }}
        - name: var-run-beyla
          emptyDir: {}
      {{- include "grafana-mltp-stack.nodeSelector" . | nindent 6 }}
      {{- include "grafana-mltp-stack.affinity" . | nindent 6 }}
      {{- include "grafana-mltp-stack.tolerations" . | nindent 6 }}
{{- end }}
