{{- if .Values.beyla.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-beyla-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "beyla" | nindent 4 }}
data:
  beyla-config.yml: |
    # Enable Kubernetes metadata collection
    attributes:
      kubernetes:
        enable: true
        cluster_name: "{{ .Values.global.clusterName | default "local" }}"
    
    # Automatic routes reporting
    routes:
      unmatched: heuristic
    
    # Service discovery configuration - use open ports method
    discovery:
      services:
        - open_ports: "4000-4002"  # Monitor mythical services ports
        - exe_path: "/usr/local/bin/node"  # Target Node.js processes
    
    # Metrics configuration
    metrics:
      interval: 5s
      features: [application, application_span]
    
    # Traces configuration  
    traces:
      features: [application, application_span]
    
    # OTEL exporter configuration
    otel_exporter_otlp:
      endpoint: http://{{ include "grafana-mltp-stack.fullname" . }}-alloy.{{ .Values.global.namespace | default .Release.Namespace }}.svc.cluster.local:4317
      insecure: true
      timeout: 30s
      
    # Log level for debugging
    log_level: info
{{- end }}
