{{- if .Values.observability.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-grafana-datasources
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "grafana" | nindent 4 }}
data:
  datasources.yaml: |
    {{- tpl (.Files.Get "configs/grafana-datasources.yaml") . | nindent 4 }}
{{- end }}
