{{- if .Values.k6.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-k6-script
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: k6-script
data:
  mythical-loadtest.js: |
    {{- tpl (.Files.Get "configs/k6-loadtest.js") . | nindent 4 }}
{{- end }}
