{{- if .Values.observability.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-loki
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "loki" | nindent 4 }}
spec:
  type: {{ if and .Values.service.autoExpose.enabled .Values.service.autoExpose.services.loki.enabled }}{{ .Values.service.type }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.observability.loki.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Values.service.autoExpose.enabled .Values.service.autoExpose.services.loki.enabled (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.autoExpose.services.loki.nodePort }}
      {{- end }}
  selector:
    {{- include "grafana-mltp-stack.componentSelectorLabels" (list . "loki") | nindent 4 }}
{{- end }}
