{{- if .Values.observability.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-loki-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "loki" | nindent 4 }}
data:
  loki.yaml: |
    {{- if and .Values.configOverrides.loki (ne .Values.configOverrides.loki "") }}
    {{- .Values.configOverrides.loki | nindent 4 }}
    {{- else }}
{{- .Files.Get "configs/loki-config.yaml" | nindent 4 }}
    {{- end }}
{{- end }}
