{{- if .Values.observability.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-loki-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "loki" | nindent 4 }}
data:
  loki.yaml: |
    {{- if and .Values.configOverrides.loki (ne .Values.configOverrides.loki "") }}
    {{- .Values.configOverrides.loki | nindent 4 }}
    {{- else }}
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info

    limits_config:
      volume_enabled: true

    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    # By default, Loki will send anonymous usage data to Grafana Labs
    # Refer https://github.com/grafana/loki/blob/main/docs/sources/configure/_index.md#analytics
    analytics:
      reporting_enabled: false

    pattern_ingester:
      enabled: true
    {{- end }}
{{- end }}
