{{- if .Values.observability.mimir.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-mimir
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "mimir" | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "grafana-mltp-stack.fullname" . }}-mimir
  # Pod management policy for StatefulSet
  podManagementPolicy: OrderedReady
  # Update strategy for StatefulSet
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "grafana-mltp-stack.componentSelectorLabels" (list . "mimir") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana-mltp-stack.labels" . | nindent 8 }}
        {{- include "grafana-mltp-stack.componentLabels" "mimir" | nindent 8 }}
    spec:
      {{- include "grafana-mltp-stack.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "grafana-mltp-stack.serviceAccountName" . }}
      {{- include "grafana-mltp-stack.podSecurityContext" . | nindent 6 }}
      containers:
        - name: mimir
          {{- include "grafana-mltp-stack.securityContext" . | nindent 10 }}
          image: "{{ .Values.observability.mimir.image.repository }}:{{ .Values.observability.mimir.image.tag }}"
          imagePullPolicy: {{ .Values.observability.mimir.image.pullPolicy }}
          args:
            - -ingester.native-histograms-ingestion-enabled=true
            - -config.file=/etc/mimir.yaml
          ports:
            - name: http
              containerPort: {{ .Values.observability.mimir.ports.http }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.development.localConfigs.enabled }}
            - name: config-volume
              mountPath: /etc/mimir.yaml
              subPath: {{ base .Values.development.localConfigs.mimir.configPath }}
              readOnly: true
            {{- else }}
            - name: config
              mountPath: /etc/mimir.yaml
              subPath: mimir.yaml
            {{- end }}
            - name: mimir-data
              mountPath: /var/mimir
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.observability.mimir.resources | nindent 12 }}
      volumes:
        {{- if .Values.development.localConfigs.enabled }}
        - name: config-volume
          hostPath:
            path: {{ .Values.development.localConfigs.basePath }}/{{ .Values.development.localConfigs.mimir.configPath }}
            type: File
        {{- else }}
        - name: config
          configMap:
            name: {{ include "grafana-mltp-stack.fullname" . }}-mimir-config
        {{- end }}
        - name: mimir-data
          emptyDir: {}
      {{- include "grafana-mltp-stack.nodeSelector" . | nindent 6 }}
      {{- include "grafana-mltp-stack.affinity" . | nindent 6 }}
      {{- include "grafana-mltp-stack.tolerations" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: mimir-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.observability.mimir.persistence.size | default "1Gi" }}
{{- end }}
