{{- if .Values.observability.mimir.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-mimir-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "mimir" | nindent 4 }}
data:
  mimir.yaml: |
    {{- if and .Values.configOverrides.mimir (ne .Values.configOverrides.mimir "") }}
    {{- .Values.configOverrides.mimir | nindent 4 }}
    {{- else }}
{{- .Files.Get "configs/mimir-config.yaml" | nindent 4 }}
    {{- end }}
{{- end }}
