{{- if .Values.microservices.requester.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-mythical-requester
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: mythical-requester
spec:
  type: {{ if and .Values.service.autoExpose.enabled .Values.service.autoExpose.services.mythicalRequester.enabled }}{{ .Values.service.type }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.microservices.requester.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Values.service.autoExpose.enabled .Values.service.autoExpose.services.mythicalRequester.enabled (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.autoExpose.services.mythicalRequester.nodePort }}
      {{- end }}
  selector:
    {{- include "grafana-mltp-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mythical-requester
{{- end }}
