{{- if .Values.infrastructure.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-postgresql-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
type: Opaque
data:
  # PostgreSQL sensitive environment variables
  POSTGRES_PASSWORD: {{ .Values.infrastructure.postgresql.auth.postgresPassword | b64enc }}
  MYTHICAL_DATABASE_PASSWORD: {{ .Values.infrastructure.postgresql.auth.postgresPassword | b64enc }}
{{- end }}
