{{- if .Values.infrastructure.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-rabbitmq-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
type: Opaque
data:
  # RabbitMQ sensitive environment variables
  RABBITMQ_PASSWORD: {{ "guest" | b64enc }}
{{- end }}
