{{- if .Values.observability.tempo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-mltp-stack.fullname" . }}-tempo-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "grafana-mltp-stack.labels" . | nindent 4 }}
    {{- include "grafana-mltp-stack.componentLabels" "tempo" | nindent 4 }}
data:
  tempo.yaml: |
    {{- if and .Values.configOverrides.tempo (ne .Values.configOverrides.tempo "") }}
    {{- .Values.configOverrides.tempo | nindent 4 }}
    {{- else }}
{{- .Files.Get "configs/tempo-config.yaml" | replace "__MIMIR_ENDPOINT__" (printf "http://%s-mimir:9009/api/v1/push" (include "grafana-mltp-stack.fullname" .)) | nindent 4 }}
    {{- end }}
{{- end }}
