# Development mode overrides for local development
development:
  mode: true
  images:
    useLocal: true
    pullPolicy: Never
    tag: latest
  localConfigs:
    enabled: false  # Keep disabled for simpler development setup

# Development namespace
global:
  namespace: mltp-dev

# Enable auto-exposure for easier development access
service:
  type: NodePort
  autoExpose:
    enabled: true
    services:
      grafana:
        enabled: true
      mythicalServer:
        enabled: true
      mythicalRequester:
        enabled: true
      mythicalRecorder:
        enabled: true
      loki:
        enabled: true
      mimir:
        enabled: true
      tempo:
        enabled: true

# Override microservices configuration for development
microservices:
  server:
    image:
      repository: mythical-beasts-server
      tag: latest
      pullPolicy: Never
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    env:
      namespace: "development"
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
  requester:
    image:
      repository: mythical-beasts-requester
      tag: latest
      pullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
      namespace: "development"
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
  recorder:
    image:
      repository: mythical-beasts-recorder
      tag: latest
      pullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
      namespace: "development"
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5

# Reduce persistence for faster development cycles
observability:
  grafana:
    persistence:
      enabled: false  # Use emptyDir for faster setup
  loki:
    persistence:
      size: "1Gi"
  mimir:
    persistence:
      size: "1Gi"
  tempo:
    persistence:
      size: "1Gi"

infrastructure:
  postgresql:
    persistence:
      size: "1Gi"
  rabbitmq:
    persistence:
      size: "1Gi"
